# This is a comment

learner:
    uc:
        username: uckaka
        password: ucpass
        dburl: someucurl

---
spring:
    profiles: de
learner:
    uc:
        username: uckaka $$$ in Germany

